## IA 651 Final Project Code Part 3

Kelsey Sheehe & Sarah Weaver

Professor Michael Gilbert

Summer 2024

## Testing Model Predictions using Linear Regression Model

In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
from pca import pca
import statsmodels.api as sm

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.svm import SVR
from sklearn import metrics
from sklearn.pipeline import Pipeline

from sklearn.tree import DecisionTreeRegressor
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.tree import plot_tree

from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

Loading the data:

In [2]:
soccer_data = pd.read_csv('nwsl-team-stats.csv')

soccer_data.head()

team_name  season  games_played  goal_differential  goals  \
0    Boston Breakers    2016            20                -33     14   
1    Boston Breakers    2017            24                -11     24   
2  Chicago Red Stars    2016            21                  3     25   
3  Chicago Red Stars    2017            25                  2     33   
4  Chicago Red Stars    2018            25                  8     38   

   goals_conceded  cross_accuracy  goal_conversion_pct  pass_pct  \
0              47           25.57                 8.97     67.38   
1              35           23.70                12.37     72.53   
2              22           21.19                11.79     67.35   
3              31           21.08                13.10     69.23   
4              30           25.96                13.67     71.63   

   pass_pct_opposition_half  possession_pct  shot_accuracy  tackle_success_pct  
0                     57.86              47          42.95               77.42  
1                     61.42              48          42.78               73.49  
2                     57.74              46          48.58               84.32  
3                     61.52              47          49.60               71.29  
4                     64.55              51          45.68               67.97

Selecting the X anf y features for linear regression (same as in the original code):

In [3]:
X = soccer_data[['games_played', 'cross_accuracy', 'goal_conversion_pct', 'pass_pct', \
'pass_pct_opposition_half', 'possession_pct', 'shot_accuracy', 'tackle_success_pct']]

y = soccer_data['goal_differential']

Creating a train test split (same as in the original code):

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Scaling the data (same as in the original code):

In [5]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Fitting the linear regression model (same as in the original code):

In [6]:
model = LinearRegression()

model.fit(X_train_scaled, y_train)

y_train_pred = model.predict(X_train_scaled)
y_test_pred = model.predict(X_test_scaled)

Obtaining the X variable coefficients (same as in the original code):

In [7]:
model.coef_

array([ 2.94146848,  3.66213088,  6.68268588, -3.89538562,  1.93705622,
        6.51269893, -0.95288718, -0.93046738])

Obtaining the intercept value (same as in the original code):

In [8]:
model.intercept_

0.34042553191488306

Obtaining MSE (same as in the original code):

In [9]:
mse_test = mean_squared_error(y_test, y_test_pred)
mse_train = mean_squared_error(y_train, y_train_pred)

print(f'Training MSE: {mse_train}')
print(f'Test MSE: {mse_test}')

Training MSE: 87.18987249386363
Test MSE: 78.94283999537852


Obtaining R Squared values (same as in the original code):

In [10]:
r2_train = r2_score(y_train,y_train_pred)
r2_test = r2_score(y_test,y_test_pred)

print(f'Training R Squared: {r2_train}')
print(f'Test R Squared: {r2_test}')

Training R Squared: 0.5390698510038272
Test R Squared: 0.7770457379462508


Randomly selecting two of the 59 rows in the data set:

In [11]:
data_test = soccer_data.sample(n=4, random_state=3)

data_test

team_name  season  games_played  goal_differential  goals  \
47  North Carolina Courage    2018            26                 41     58   
18         NJ/NY Gotham FC    2018            24                -31     21   
56    Racing Louisville FC    2022            22                -12     23   
13            Houston Dash    2019            24                -15     21   

    goals_conceded  cross_accuracy  goal_conversion_pct  pass_pct  \
47              17           33.16                14.15     71.06   
18              52           24.91                 9.38     72.07   
56              35           20.18                11.50     72.50   
13              36           20.27                 9.33     73.27   

    pass_pct_opposition_half  possession_pct  shot_accuracy  \
47                     63.15              50          46.10   
18                     63.06              48          45.54   
56                     62.09              49          42.00   
13                     62.45              48          45.78   

    tackle_success_pct  
47               73.84  
18               70.29  
56               62.87  
13               60.61

Creating the X data for testing on the linear regression model:

In [12]:
x_data_test = data_test[['games_played','cross_accuracy','goal_conversion_pct','pass_pct','pass_pct_opposition_half','possession_pct','shot_accuracy','tackle_success_pct']]

x_data_test

games_played  cross_accuracy  goal_conversion_pct  pass_pct  \
47            26           33.16                14.15     71.06   
18            24           24.91                 9.38     72.07   
56            22           20.18                11.50     72.50   
13            24           20.27                 9.33     73.27   

    pass_pct_opposition_half  possession_pct  shot_accuracy  \
47                     63.15              50          46.10   
18                     63.06              48          45.54   
56                     62.09              49          42.00   
13                     62.45              48          45.78   

    tackle_success_pct  
47               73.84  
18               70.29  
56               62.87  
13               60.61

scaling the X data:

In [13]:
scaler = StandardScaler()
x_data_test_scaled = scaler.fit_transform(x_data_test)

making a prediction:

In [14]:
data_predict = model.predict(x_data_test_scaled)

data_predict

array([ 36.41755197,  -9.72625897,  -5.2005303 , -20.12906057])

### Making synthetic Data:

In [15]:
soccer_data.describe()

season  games_played  goal_differential      goals  \
count    59.000000     59.000000          59.000000  59.000000   
mean   2018.949153     23.593220           0.491525  31.254237   
std       2.223881      1.772575          15.054353  10.411521   
min    2016.000000     20.000000         -33.000000  12.000000   
25%    2017.000000     22.000000          -8.000000  23.500000   
50%    2019.000000     24.000000           2.000000  30.000000   
75%    2021.000000     25.000000          10.000000  37.000000   
max    2022.000000     27.000000          41.000000  62.000000   

       goals_conceded  cross_accuracy  goal_conversion_pct   pass_pct  \
count       59.000000       59.000000            59.000000  59.000000   
mean        30.762712       23.829153            12.804407  73.234068   
std          8.173420        2.720766             3.000926   3.450056   
min         17.000000       18.420000             5.430000  62.600000   
25%         24.000000       22.285000            10.860000  71.360000   
50%         31.000000       23.640000            13.100000  72.560000   
75%         35.000000       25.140000            14.855000  76.325000   
max         52.000000       33.160000            20.000000  79.990000   

       pass_pct_opposition_half  possession_pct  shot_accuracy  \
count                 59.000000       59.000000      59.000000   
mean                  63.746271       50.033898      46.563220   
std                    3.976299        3.162093       3.988194   
min                   53.710000       41.000000      35.190000   
25%                   61.480000       48.000000      44.015000   
50%                   62.970000       50.000000      46.540000   
75%                   65.325000       52.500000      49.030000   
max                   72.140000       58.000000      54.020000   

       tackle_success_pct  
count           59.000000  
mean            67.517627  
std              8.643450  
min             56.870000  
25%             59.660000  
50%             65.450000  
75%             73.860000  
max             86.340000

Using the mean for each x variable used in the linear regression model and going 2 standard deviations away in a positive or negative way to make a "good" team and a "bad" team 

In [16]:
synthetic_data = {'team': ['Good Team','Bad Team'],'games_played': [23.593220, 23.593220], 'cross_accuracy': [29.270685, 18.387621], 'goal_conversion_pct': [18.806259, 6.802555], \
    'pass_pct': [80.13418, 66.333956], 'pass_pct_opposition_half': [71.698869, 55.793673], 'possession_pct': [56.358084, 43.709712], 'shot_accuracy': [54.539608, 38.586832], \
        'tackle_success_pct': [84.804572, 50.230772]}

synthetic_df = pd.DataFrame(synthetic_data)

synthetic_df

team  games_played  cross_accuracy  goal_conversion_pct   pass_pct  \
0  Good Team      23.59322       29.270685            18.806259  80.134180   
1   Bad Team      23.59322       18.387621             6.802555  66.333956   

   pass_pct_opposition_half  possession_pct  shot_accuracy  tackle_success_pct  
0                 71.698869       56.358084      54.539608           84.804572  
1                 55.793673       43.709712      38.586832           50.230772

Selecting the features for linear regression:

In [17]:
x_synthetic_data = synthetic_df[['games_played','cross_accuracy','goal_conversion_pct','pass_pct','pass_pct_opposition_half','possession_pct','shot_accuracy','tackle_success_pct']]

x_synthetic_data 


games_played  cross_accuracy  goal_conversion_pct   pass_pct  \
0      23.59322       29.270685            18.806259  80.134180   
1      23.59322       18.387621             6.802555  66.333956   

   pass_pct_opposition_half  possession_pct  shot_accuracy  tackle_success_pct  
0                 71.698869       56.358084      54.539608           84.804572  
1                 55.793673       43.709712      38.586832           50.230772

Scaling the data:

In [18]:
scaler = StandardScaler()
x_synthetic_test_scaled = scaler.fit_transform(x_synthetic_data)

Predicting goal_differential from the linear regression:

In [19]:
synthetic_data_predict = model.predict(x_synthetic_test_scaled)

synthetic_data_predict

array([ 13.35625727, -12.6754062 ])